### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by dboudreaux** [HCLmainframetools/mainframeToolsDocs#1]
Getting the following error when i tried to run the second step in the "Deploy HCL Tools step`'

The given result could not be parsed: 'IKJ56716I EXTRANEOUS INFORMATION WAS IGNORED: 'TRAVIST.EXEC(HCLREXX 
IKJ56712I INVALID KEYWORD, '
IKJ56703A REENTER THIS OPERAND -   
'.

**Comment by travatine** [comment]
Hi @dboudreaux , 

Thanks for using HCL z Tools.

The deploy command uses the data set name 'TRAVIST.EXEC' as an example.

Could you please try using '<userid>.ZTOOLS.EXEC' as the 'HCLRexx exec data set name'?
(where '<userid>' is user id that you use to connect to your z/OS system.)

Thanks,

Travis Thorne.

**Comment by dboudreaux** [comment]
Hi Travis… Sorry but I am confused.

I issued a command in VS Code (“Deploy HCL Z TOOLS” (or something like that). It started allocating datasets. It created HLQ.TEMP.HCLTOOLS.XMIT.TRS ; it then seems to expand something, and then it starts to create another dataset (without TRS on the end). It then unpacks and It is at this point things fail. I don’t understand where TRAVIST.EXEC is specified.

My userid is in a zowe profile.

Dana
dana.boudreau@gmail.com

**Comment by travatine** [comment]
Hi ,

Apologies for the confusion,

The 'HCL z Tools' data set names are stored in the VS Code extension preferences.

You can navigate to the preferences with these steps:
- Click on the VS Code 'File' menu
- Click 'Preferences'
- Click 'Settings'
- Expand 'Extensions'
- Click on 'HCL z Tools'

The preferences  'Hcl Backend Exec Data Set Name'  and 
 'Hcl Backend Program Library Data Set Name' are used by the "deploy" commands.

If you update the preferences , the new values will appear the next time you run the deploy commands.

Travis Thorne

**Comment by dboudreaux** [comment]
Getting a similar error:
The given result could not be parsed: 'IKJ56716I EXTRANEOUS INFORMATION WAS IGNORED: '.ZTOOLS.EXEC(HCLREXX
IKJ56712I INVALID KEYWORD, ‘
IKJ56703A REENTER THIS OPERAND -
‘.

My settings:


Dana
dana.boudreau@gmail.com

**Comment by travatine** [comment]
Hi,

Sorry In my message above, I used `<userid>` without realizing I needed a code block tag .
The dataset names need to specify fully qualified dataset names ( apostrophes or quotes are not required).

For example, my TSO userid is `TRAVIST`, so for the exec data set name, I'd specify,
`TRAVIST.ZTOOLS.EXEC`

Travis

**Comment by dboudreaux** [comment]
I am still getting:
The given result could not be parsed: 'IKJ56716I EXTRANEOUS INFORMATION WAS IGNORED: 'BOUDA06.ZTOOLS.EXEC(HCLREXX
IKJ56712I INVALID KEYWORD, ‘
IKJ56703A REENTER THIS OPERAND -
‘.

My setting json is: (my HLQ=bouda06


Dana
dana.boudreau@gmail.com

**Comment by travatine** [comment]
Hi Dana,

I think the problem is being caused by by initial attempt at MVS data set name validation; I was only checking the name length was between 3 and 44 characters . 

This "bug" means that invalid data set names ( such as those including spaces or quotes or apostrophes) can be specified ; unfortunately these will cause the deploy command to fail.

In the next update of HCL z Tools , I will be implementing  much more strict data set name validation (  based on IBM data set naming conventions / rules).

I'm also considering if I should provide a "manual" deploy option in the future. This could allow the "REXX" exec and "terse packed program" to be sent to your Mainframe using FTP, then unpacked using batch JCL.

Travis.

**Comment by travatine** [comment]
Hi @dboudreaux ,

I've just published HCL z Tools 0.0.6 , it includes a new "manual deployment" command that allows ftp and jcl to be used to deploy the backend:

![manual-deploy](https://user-images.githubusercontent.com/17565183/81255485-507f4680-9060-11ea-89f7-219cde97699f.gif)

Please let me know if this new option helps with the installation issues you were having.

Thanks,
Travis.

**Comment by travatine** [comment]
Hi,
I'm guessing this is now resolved, please reopen this issue if not.
