### ISSUE TITLE
HCL z tools disables/dis-associates the Bitlang JCL parser

### ISSUE THREAD

**Issue by venkatzhub** [HCLmainframetools/mainframeToolsDocs#2]
In my VSCode installation, I have the Bitlang COBOL extension that provides the syntax highlighting for COBOL, JCL etc. 

Without the HCL z Tools extension, if I open a JCL member using Zowe explorer - I get all the syntax highlighting. I right click in the editor - and the menu doesn't have Submit Job

Once the HCL z Tools extension is installed, and I open the same JCL member - there is no syntax highlighting. I right click in the editor - and the menu does show Submit Job - but the issue is the JCL syntax highlighting is lost. 

I "Disabled" HLC z tools - just to check, and when I open the JCL member with HCLz tools disabled, the syntax highlighting is back.

**Comment by travatine** [comment]
Hi @venkatzhub ,

I can reproduce this problem.

I'm going to remove the "JCL" language definition from "HCL z Tools" to prevent conflicts like this.

The fix will be in the next version of HCL z Tools

**Comment by travatine** [comment]
Hi @venkatzhub ,
HCL z Tools v0.0.6 is now available and includes a fix for this issue:

![Untitled Project](https://user-images.githubusercontent.com/17565183/81255257-cf27b400-905f-11ea-8149-975e3dfc4291.gif)

Can you please let me know if your issue is resolved?

Thanks,
Travis.

**Comment by travatine** [comment]
Hi,
I'm guessing this is now resolved, please reopen this issue if not.
