### ISSUE TITLE
 Error: Failed to load data The given result could not be parsed: 'IKJ56700A ENTER REGION SIZE - '

### ISSUE THREAD

**Issue by shameemSIX** [HCLmainframetools/mainframeToolsDocs#4]
After successful deployment of HCL z Tools all further operation ends with error 

Error: Failed to load data The given result could not be parsed: 'IKJ56700A ENTER REGION SIZE - '

![error 1](https://user-images.githubusercontent.com/75373880/100878043-f1749980-34a9-11eb-9888-56008fddc1d8.png)

**Comment by shameemSIX** [comment]
[Console Error.txt](https://github.com/HCLmainframetools/mainframeToolsDocs/files/5629604/Console.Error.txt)
Error from console is attached for reference

**Comment by shameemSIX** [comment]
I could see the script from HCL z Tools requesting a region size of 409600. This was above the max limit on my userid TSO segment. 
I have changed my MaxKB to a value higher than 409600 and that resolved the issue. 

Thanks and i am closing this issue.

**Comment by travatine** [comment]
Hi,

Thanks for using HCL z Tools.

Please, what was your default TSO region size limit?

Kind Regards,
Travis Thorne.
